spring:
  cloud:
    gateway:
      routes:
        - id: demo-api
          uri: lb://demo-api
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1
        - id: example-api
          uri: lb://example-api
          predicates:
            - Path=/example/**
          filters:
            - StripPrefix=1